package com.cooksys.neverland.models;

// Generated May 17, 2016 5:58:09 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "neverland")
public class Location implements java.io.Serializable
{

	private Integer locationId;
	private String city;
	private String state;
	@JsonIgnore
	private Set<Flight> flightsForDestinationLocation = new HashSet<Flight>(0);
	@JsonIgnore
	private Set<Flight> flightsForOriginLocation = new HashSet<Flight>(0);

	public Location()
	{
	}

	public Location(String city, String state)
	{
		this.city = city;
		this.state = state;
	}

	public Location(String city, String state,
			Set<Flight> flightsForDestinationLocation,
			Set<Flight> flightsForOriginLocation)
	{
		this.city = city;
		this.state = state;
		this.flightsForDestinationLocation = flightsForDestinationLocation;
		this.flightsForOriginLocation = flightsForOriginLocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "location_id", unique = true, nullable = false)
	public Integer getLocationId()
	{
		return this.locationId;
	}

	public void setLocationId(Integer locationId)
	{
		this.locationId = locationId;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity()
	{
		return this.city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	@Column(name = "state", nullable = false, length = 45)
	public String getState()
	{
		return this.state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationByDestinationLocation")
	public Set<Flight> getFlightsForDestinationLocation()
	{
		return this.flightsForDestinationLocation;
	}

	public void setFlightsForDestinationLocation(
			Set<Flight> flightsForDestinationLocation)
	{
		this.flightsForDestinationLocation = flightsForDestinationLocation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationByOriginLocation")
	public Set<Flight> getFlightsForOriginLocation()
	{
		return this.flightsForOriginLocation;
	}

	public void setFlightsForOriginLocation(Set<Flight> flightsForOriginLocation)
	{
		this.flightsForOriginLocation = flightsForOriginLocation;
	}

}
